CONFIG_SYS_CLOCK_TICKS_PER_SEC=100000

CONFIG_SCHED_DEADLINE=y
CONFIG_QEMU_ICOUNT=n
CONFIG_STDOUT_CONSOLE=y

CONFIG_REQUIRES_FLOAT_PRINTF=y      # OVERHEAD MEASUREMENT #
CONFIG_NEWLIB_LIBC_FLOAT_PRINTF=y   # OVERHEAD MEASUREMENT #